services:
  - type: web
    name: avante-servico
    env: php
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_PORT
        value: 3306
      - key: APP_ENV
        value: production

databases:
  - name: avante-servico-db
    databaseName: avante_servico
    user: avante_user
